project:
  type: book
  output-dir: _site

execute: 
  enabled: true

lang: bg
book:
  title: "Въведение в линейната оптимизация"
  author: "Бойко Амаров"
  date: last-modified
  
  chapters:
    - index.qmd
    - Literature.qmd
    # - part: 01-Python/index.qmd
    - 02-Introduction/index.ipynb
    - 03-Graphical-Method/01-Blending.ipynb
    - 03-Graphical-Method/02-Sensitivity.ipynb
#    - 04-Simplex/01-Canonical-Representation.ipynb
    - 04-Simplex/01-Simplex-Method.ipynb
    - 04-Simplex/02-Simplex-Method-3D.ipynb
    - 04-Simplex/03-Simplex-Method-Edge.ipynb
    - 04-Duals.qmd
    - 05-Sensitivity.qmd
    - 06-Transportation.ipynb
    - 00-Assignments/assignments.ipynb
    # - 00-Assignments/covid-facilities.ipynb
      # chapters:
      #   - 01-Python/01-01-Basics.ipynb
      #   - 01-Python/01-02-Basics-Ex.ipynb
      #   - 01-Python/01-03-Numpy.ipynb
      #   - 01-Python/01-04-Pandas.ipynb
      #   - 01-Python/01-05-Pandas-Ex.ipynb        
    # - 00-Homework-Instructions.qmd
    # - 02-Statistics-Review.qmd
    # - 01-Introduction-to-R.qmd
    # - 02a-Continuous-Distributions.qmd
    # - 03-Simple-Linear-Model.qmd
    # - 04-Simple-ANOVA.qmd
    # - 05-Hypothesis-Testing-and-CI.qmd
    # - izpit.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    code-fold: true
    code-summary: "Покажи"
    execute:
      enable: true

editor: visual
