name: opt2025-de
channels:
  - gurobi
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.0=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - anyio=4.6.2=py311h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311h06a4308_0
  - attrs=24.3.0=py311h06a4308_0
  - babel=2.16.0=py311h06a4308_0
  - beautifulsoup4=4.12.3=py311h06a4308_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=openblas
  - bleach=6.2.0=py311h06a4308_0
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2025.1.31=py311h06a4308_0
  - cffi=1.17.1=py311h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py311h06a4308_0
  - contourpy=1.3.1=py311hdb19cb5_0
  - curl=8.11.1=hdbd6064_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.55.3=py311h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gfortran_impl_linux-64=11.2.0=h1234567_1
  - gfortran_linux-64=11.2.0=hc2dff05_2
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gurobi=12.0.1=py311_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - h11=0.14.0=py311h06a4308_0
  - harfbuzz=10.2.0=hf296adc_0
  - httpcore=1.0.2=py311h06a4308_0
  - httpx=0.27.0=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py311h06a4308_1
  - ipython=8.30.0=py311h06a4308_0
  - ipywidgets=8.1.5=py311h06a4308_0
  - jedi=0.19.2=py311h06a4308_0
  - jinja2=3.1.5=py311h06a4308_0
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.25=py311h06a4308_0
  - jsonschema=4.23.0=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jupyter=1.1.1=py311h06a4308_0
  - jupyter-lsp=2.2.0=py311h06a4308_0
  - jupyter_client=8.6.3=py311h06a4308_0
  - jupyter_console=6.6.3=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - jupyter_events=0.10.0=py311h06a4308_0
  - jupyter_server=2.14.1=py311h06a4308_0
  - jupyter_server_terminals=0.4.4=py311h06a4308_1
  - jupyterlab=4.3.4=py311h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py311h06a4308_0
  - jupyterlab_widgets=3.0.13=py311h06a4308_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - kiwisolver=1.4.8=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.11.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.2=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - make=4.2.1=h1bed415_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib=3.10.0=py311h06a4308_0
  - matplotlib-base=3.10.0=py311hbfdbfaf_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mistune=2.0.4=py311h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mysql=8.4.0=h29a9f33_1
  - nbclient=0.8.0=py311h06a4308_0
  - nbconvert=7.16.4=py311h06a4308_0
  - nbformat=5.10.4=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - notebook=7.3.2=py311h06a4308_0
  - notebook-shim=0.2.3=py311h06a4308_0
  - numexpr=2.10.1=py311hd28fd6d_0
  - numpy=2.2.2=py311h24aa872_0
  - numpy-base=2.2.2=py311hbfb1bba_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.16=h5eee18b_0
  - overrides=7.4.0=py311h06a4308_0
  - packaging=24.2=py311h06a4308_0
  - pandas=2.2.3=py311h6a678d5_0
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.7=h0fee60c_1
  - parso=0.8.4=py311h06a4308_0
  - patsy=1.0.1=py311h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.1.0=py311hcea889d_0
  - pip=25.0=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=3.10.0=py311h06a4308_0
  - plotly=5.24.1=py311h92b7b1e_0
  - ply=3.11=py311h06a4308_0
  - prometheus_client=0.21.0=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.2.0=py311h06a4308_0
  - pypng=0.20220715.0=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_1
  - pyqt5-sip=12.13.0=py311h5eee18b_1
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.11=he870216_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-fastjsonschema=2.20.0=py311h06a4308_0
  - python-json-logger=3.2.1=py311h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py311h06a4308_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=26.2.0=py311h6a678d5_0
  - qrcode=7.4.2=py311h06a4308_0
  - qt-main=5.15.2=hb6262e9_12
  - qtconsole=5.6.1=py311h06a4308_0
  - qtpy=2.4.1=py311h06a4308_0
  - r-askpass=1.2.0=r43h76d94ec_0
  - r-backports=1.4.1=r43h76d94ec_0
  - r-base=4.3.1=h1ae530e_0
  - r-base64enc=0.1_3=r43h76d94ec_4
  - r-bit=4.0.5=r43h76d94ec_0
  - r-bit64=4.0.5=r43h76d94ec_0
  - r-blob=1.2.4=r43h6115d3f_0
  - r-brio=1.1.3=r43h76d94ec_0
  - r-broom=1.0.5=r43h6115d3f_0
  - r-bslib=0.5.1=r43h6115d3f_0
  - r-cachem=1.0.8=r43h76d94ec_0
  - r-callr=3.7.3=r43h6115d3f_0
  - r-cellranger=1.1.0=r43h6115d3f_0
  - r-cli=3.6.1=r43h884c59f_0
  - r-clipr=0.8.0=r43h6115d3f_0
  - r-colorspace=2.1_0=r43h76d94ec_0
  - r-conflicted=1.2.0=r43h142f84f_0
  - r-cpp11=0.4.6=r43h6115d3f_0
  - r-crayon=1.5.2=r43h6115d3f_0
  - r-curl=5.1.0=r43h76d94ec_0
  - r-data.table=1.14.8=r43h76d94ec_0
  - r-dbi=1.1.3=r43h6115d3f_0
  - r-dbplyr=2.3.4=r43h6115d3f_0
  - r-desc=1.4.2=r43h6115d3f_0
  - r-diffobj=0.3.5=r43h76d94ec_0
  - r-digest=0.6.33=r43h884c59f_0
  - r-dplyr=1.1.3=r43h884c59f_0
  - r-dtplyr=1.3.1=r43h6115d3f_0
  - r-ellipsis=0.3.2=r43h76d94ec_0
  - r-evaluate=0.22=r43h6115d3f_0
  - r-fansi=1.0.5=r43h76d94ec_0
  - r-farver=2.1.1=r43h884c59f_0
  - r-fastmap=1.1.1=r43h884c59f_0
  - r-fontawesome=0.5.2=r43h6115d3f_0
  - r-forcats=1.0.0=r43h6115d3f_0
  - r-fs=1.6.3=r43h884c59f_0
  - r-gargle=1.5.2=r43h142f84f_0
  - r-generics=0.1.3=r43h142f84f_0
  - r-ggplot2=3.4.4=r43h6115d3f_0
  - r-glue=1.6.2=r43h76d94ec_0
  - r-googledrive=2.1.1=r43h6115d3f_0
  - r-googlesheets4=1.1.1=r43h6115d3f_0
  - r-gtable=0.3.4=r43h6115d3f_0
  - r-haven=2.5.3=r43h884c59f_0
  - r-highr=0.10=r43h6115d3f_0
  - r-hms=1.1.3=r43h6115d3f_0
  - r-htmltools=0.5.6.1=r43h76d94ec_0
  - r-httr=1.4.7=r43h6115d3f_0
  - r-ids=1.0.1=r43h142f84f_0
  - r-isoband=0.2.7=r43h884c59f_0
  - r-jquerylib=0.1.4=r43h6115d3f_0
  - r-jsonlite=1.8.7=r43h76d94ec_0
  - r-knitr=1.44=r43h6115d3f_0
  - r-labeling=0.4.3=r43h6115d3f_0
  - r-lattice=0.22_5=r43h76d94ec_0
  - r-lifecycle=1.0.3=r43h142f84f_0
  - r-lubridate=1.9.3=r43h76d94ec_0
  - r-magrittr=2.0.3=r43h76d94ec_0
  - r-mass=7.3_60=r43h76d94ec_0
  - r-matrix=1.6_1.1=r43h76d94ec_0
  - r-memoise=2.0.1=r43h6115d3f_0
  - r-mgcv=1.9_0=r43h76d94ec_0
  - r-mime=0.12=r43h76d94ec_0
  - r-modelr=0.1.11=r43h6115d3f_0
  - r-munsell=0.5.0=r43h6115d3f_0
  - r-nlme=3.1_163=r43h640688f_0
  - r-openssl=2.1.1=r43h76d94ec_0
  - r-ottr=1.5.1=r43hc72bb7e_0
  - r-pillar=1.9.0=r43h6115d3f_0
  - r-pkgbuild=1.4.2=r43h142f84f_0
  - r-pkgconfig=2.0.3=r43h6115d3f_0
  - r-pkgload=1.3.3=r43h142f84f_0
  - r-praise=1.0.0=r43h6115d3f_4
  - r-prettyunits=1.2.0=r43h142f84f_0
  - r-processx=3.8.2=r43h76d94ec_0
  - r-progress=1.2.2=r43h142f84f_0
  - r-ps=1.7.5=r43h76d94ec_0
  - r-purrr=1.0.2=r43h76d94ec_0
  - r-r6=2.5.1=r43h6115d3f_0
  - r-ragg=1.2.6=r43h884c59f_0
  - r-rappdirs=0.3.3=r43h76d94ec_0
  - r-rcolorbrewer=1.1_3=r43h6115d3f_1
  - r-readr=2.1.4=r43h884c59f_0
  - r-readxl=1.4.3=r43h884c59f_0
  - r-rematch=2.0.0=r43h6115d3f_0
  - r-rematch2=2.1.2=r43h142f84f_0
  - r-reprex=2.0.2=r43h6115d3f_0
  - r-rlang=1.1.1=r43h884c59f_0
  - r-rmarkdown=2.25=r43h6115d3f_0
  - r-rprojroot=2.0.3=r43h6115d3f_0
  - r-rstudioapi=0.15.0=r43h6115d3f_0
  - r-rvest=1.0.3=r43h6115d3f_0
  - r-sass=0.4.7=r43h884c59f_0
  - r-scales=1.2.1=r43h6115d3f_0
  - r-selectr=0.4_2=r43h6115d3f_0
  - r-stringi=1.7.12=r43h884c59f_0
  - r-stringr=1.5.0=r43h6115d3f_0
  - r-sys=3.4.2=r43h76d94ec_0
  - r-systemfonts=1.0.5=r43h884c59f_0
  - r-testthat=3.2.3=r43h93ab643_0
  - r-textshaping=0.3.7=r43h884c59f_0
  - r-tibble=3.2.1=r43h76d94ec_0
  - r-tidyr=1.3.0=r43h884c59f_0
  - r-tidyselect=1.2.0=r43h6115d3f_0
  - r-tidyverse=2.0.0=r43h785f33e_2
  - r-timechange=0.2.0=r43h884c59f_0
  - r-tinytex=0.48=r43h142f84f_0
  - r-tzdb=0.4.0=r43h884c59f_0
  - r-utf8=1.2.4=r43h76d94ec_0
  - r-uuid=1.1_1=r43h76d94ec_0
  - r-vctrs=0.6.4=r43h884c59f_0
  - r-viridislite=0.4.2=r43h6115d3f_0
  - r-vroom=1.6.4=r43h884c59f_0
  - r-waldo=0.5.1=r43h6115d3f_0
  - r-withr=2.5.1=r43h6115d3f_0
  - r-xfun=0.40=r43h76d94ec_0
  - r-xml2=1.3.6=r43h884c59f_0
  - r-yaml=2.3.7=r43h76d94ec_0
  - r-zip=2.3.0=r43h76d94ec_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py311h06a4308_0
  - requests=2.32.3=py311h06a4308_1
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rpds-py=0.22.3=py311h4aa5aa6_0
  - rpy2=3.5.11=py311r43h356210d_0
  - scikit-learn=1.6.1=py311h6a678d5_0
  - scipy=1.15.1=py311h24aa872_0
  - seaborn=0.13.2=py311h06a4308_1
  - send2trash=1.8.2=py311h06a4308_1
  - setuptools=72.1.0=py311h06a4308_0
  - simplegeneric=0.8.1=py311h06a4308_2
  - sip=6.7.12=py311h6a678d5_1
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py311h06a4308_0
  - soupsieve=2.5=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=9.0.0=py311h06a4308_0
  - terminado=0.17.1=py311h06a4308_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tinycss2=1.4.0=py311h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tktable=2.10=h3d55465_1
  - tornado=6.4.2=py311h5eee18b_0
  - traitlets=5.14.3=py311h06a4308_0
  - typing-extensions=4.12.2=py311h06a4308_0
  - typing_extensions=4.12.2=py311h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - tzlocal=5.2=py311h06a4308_0
  - unicodedata2=15.1.0=py311h5eee18b_1
  - urllib3=2.3.0=py311h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=1.8.0=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - widgetsnbextension=4.0.13=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - alabaster==1.0.0
      - annotated-types==0.7.0
      - click==8.1.8
      - dill==0.3.9
      - docutils==0.21.2
      - fica==0.4.1
      - greenlet==3.1.1
      - imagesize==1.4.1
      - ipylab==1.0.0
      - jupytext==1.16.7
      - markdown-it-py==3.0.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - networkx==3.4.2
      - otter-grader==6.1.0
      - playwright==1.50.0
      - polytope==0.2.5
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyee==12.1.1
      - pygments==2.19.1
      - python-on-whales==0.75.1
      - snowballstemmer==2.2.0
      - sphinx==8.1.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - wrapt==1.17.2
prefix: /home/amarov/miniconda3/envs/opt2025-de
